<option value="0">Select One</option>
<option value="100Ft Road">100Ft Road</option>
<option value="3rd Parallel Road">3rd Parallel Road</option>
<option value="60 Ft Road">60 Ft Road</option>
<option value="Adityanagar">Adityanagar</option>
<option value="Agara">Agara</option>
<option value="Agrahara">Agrahara</option>
<option value="Airport Road">Airport Road</option>
<option value="Akshaya Nagar">Akshaya Nagar</option>
<option value="Amrutahalli">Amrutahalli</option>
<option value="Ananthpur Road">Ananthpur Road</option>
<option value="Anjanapura">Anjanapura</option>
<option value="Anna Nagar">Anna Nagar</option>
<option value="Annapurneshwari Nagar">Annapurneshwari Nagar</option>
<option value="Arabic College">Arabic College</option>
<option value="Arekere Gate">Arekere Gate</option>
<option value="Ashoka Road">Ashoka Road</option>
<option value="Ashoknagar">Ashoknagar</option>
<option value="Ashwat Nagar">Ashwat Nagar</option>
<option value="Audugodi">Audugodi</option>
<option value="Austin Town">Austin Town</option>
<option value="Avalahalli">Avalahalli</option>
<option value="Avenue Road">Avenue Road</option>
<option value="Azad Nagar">Azad Nagar</option>
<option value="Balaraj Urs Road">Balaraj Urs Road</option>
<option value="Balepete">Balepete</option>
<option value="Bamboo Bazar">Bamboo Bazar</option>
<option value="Banashankari">Banashankari</option>
<option value="Banaswadi">Banaswadi</option>
<option value="Bangalore City">Bangalore City</option>
<option value="Bangalore GPO">Bangalore GPO</option>
<option value="Bangalore Mysore Highway">Bangalore Mysore Highway</option>
<option value="Bangalore Road">Bangalore Road</option>
<option value="Bank Colony">Bank Colony</option>
<option value="Bannerghatta Main Road">Bannerghatta Main Road</option>
<option value="Bannimantap">Bannimantap</option>
<option value="Basavanagudi">Basavanagudi</option>
<option value="Basaveshwara Nagar">Basaveshwara Nagar</option>
<option value="Battarahalli">Battarahalli</option>
<option value="Bejjavalli">Bejjavalli</option>
<option value="Bellandur">Bellandur</option>
<option value="Benamangala Layout">Benamangala Layout</option>
<option value="Benson Town">Benson Town</option>
<option value="BH Road">BH Road</option>
<option value="Bhoopasandra Main Road">Bhoopasandra Main Road</option>
<option value="Bilekahalli">Bilekahalli</option>
<option value="Binnamangala">Binnamangala</option>
<option value="Binnypet">Binnypet</option>
<option value="BN Road">BN Road</option>
<option value="Bogadi">Bogadi</option>
<option value="Bommanahalli">Bommanahalli</option>
<option value="Bommasandra">Bommasandra</option>
<option value="Brigade Road">Brigade Road</option>
<option value="Brookefield">Brookefield</option>
<option value="Brunton Road">Brunton Road</option>
<option value="BTM Layout">BTM Layout</option>
<option value="BTM Layout 2nd Stage">BTM Layout 2nd Stage</option>
<option value="Bull Temple Road">Bull Temple Road</option>
<option value="BVK Iyengar Road">BVK Iyengar Road</option>
<option value="Byappanahalli">Byappanahalli</option>
<option value="Byatarayanapura">Byatarayanapura</option>
<option value="Cambridge Layout">Cambridge Layout</option>
<option value="Cantonment">Cantonment</option>
<option value="Cantonment">Cantonment</option>
<option value="Carmelaram">Carmelaram</option>
<option value="Central Street">Central Street</option>
<option value="Chakravarthy Layout">Chakravarthy Layout</option>
<option value="Challaghatta">Challaghatta</option>
<option value="Chamarajapet">Chamarajapet</option>
<option value="Chamarajapura">Chamarajapura</option>
<option value="Chandapura">Chandapura</option>
<option value="Chandra Layout">Chandra Layout</option>
<option value="Chandragupta Road">Chandragupta Road</option>
<option value="Channasandra">Channasandra</option>
<option value="Chikkabanavara">Chikkabanavara</option>
<option value="Chikkalsandra">Chikkalsandra</option>
<option value="Chikkamavalli">Chikkamavalli</option>
<option value="Chikkayarahalli">Chikkayarahalli</option>
<option value="Chikpete">Chikpete</option>
<option value="Cholanayakkanahilli">Cholanayakkanahilli</option>
<option value="Chunchghatta">Chunchghatta</option>
<option value="Church Street">Church Street</option>
<option value="City Market">City Market</option>
<option value="CMH Road">CMH Road</option>
<option value="Coles Road">Coles Road</option>
<option value="College Road">College Road</option>
<option value="Commercial Street">Commercial Street</option>
<option value="Cooke Town">Cooke Town</option>
<option value="Cottonpet">Cottonpet</option>
<option value="Court Road">Court Road</option>
<option value="Cox Town">Cox Town</option>
<option value="Cresent Road">Cresent Road</option>
<option value="Cubbon Park">Cubbon Park</option>
<option value="Cunningham Road">Cunningham Road</option>
<option value="CV Raman Nagar">CV Raman Nagar</option>
<option value="Dasarahalli">Dasarahalli</option>
<option value="Davangere">Davangere</option>
<option value="Devanahalli">Devanahalli</option>
<option value="Devarachikkanahalli">Devarachikkanahalli</option>
<option value="Devaraja Mohalla">Devaraja Mohalla</option>
<option value="Devasandra">Devasandra</option>
<option value="Devraj Urs Road">Devraj Urs Road</option>
<option value="Dewans Road">Dewans Road</option>
<option value="Dharmaram College">Dharmaram College</option>
<option value="Dickenson Road">Dickenson Road</option>
<option value="Dodda Banaswadi">Dodda Banaswadi</option>
<option value="Dodda Bomasandra">Dodda Bomasandra</option>
<option value="Dodda Nakkundi">Dodda Nakkundi</option>
<option value="Doddakallasandra ">Doddakallasandra </option>
<option value="Dodkunte">Dodkunte</option>
<option value="Dollars Colony">Dollars Colony</option>
<option value="Domlur">Domlur</option>
<option value="Dooravani Nagar">Dooravani Nagar</option>
<option value="Double Road">Double Road</option>
<option value="Durgigudi">Durgigudi</option>
<option value="DVG Road">DVG Road</option>
<option value="Dwarakanagar">Dwarakanagar</option>
<option value="Ejipura">Ejipura</option>
<option value="Electronics City">Electronics City</option>
<option value="Fort Mohalla">Fort Mohalla</option>
<option value="Frazer Town">Frazer Town</option>
<option value="G.K.V.K">G.K.V.K</option>
<option value="Gajanur">Gajanur</option>
<option value="Gandhi Bazaar">Gandhi Bazaar</option>
<option value="Gandhi Bazar">Gandhi Bazar</option>
<option value="Gandhi Square">Gandhi Square</option>
<option value="Gandhinagar">Gandhinagar</option>
<option value="Ganga Nagar">Ganga Nagar</option>
<option value="Ganjam">Ganjam</option>
<option value="Garden Area">Garden Area</option>
<option value="Gavipuram">Gavipuram</option>
<option value="Gayathripuram">Gayathripuram</option>
<option value="Geetha Colony">Geetha Colony</option>
<option value="Girinagar">Girinagar</option>
<option value="Gokula  Extension">Gokula  Extension</option>
<option value="Gokula Extension">Gokula Extension</option>
<option value="Gokulam">Gokulam</option>
<option value="Golf Course Road">Golf Course Road</option>
<option value="Gopi Circle">Gopi Circle</option>
<option value="Guttahalli">Guttahalli</option>
<option value="HAL">HAL</option>
<option value="HAL 2nd Stage">HAL 2nd Stage</option>
<option value="HAL 3rd Stage">HAL 3rd Stage</option>
<option value="Halladakeri">Halladakeri</option>
<option value="Hampi">Hampi</option>
<option value="Hanumantha Rao Street">Hanumantha Rao Street</option>
<option value="Hanumanthanagar">Hanumanthanagar</option>
<option value="Hardinge Circle">Hardinge Circle</option>
<option value="HBR Layout">HBR Layout</option>
<option value="HBR Layout">HBR Layout</option>
<option value="Hebbal">Hebbal</option>
<option value="Hebbal">Hebbal</option>
<option value="Hegganahalli">Hegganahalli</option>
<option value="Hennur Road">Hennur Road</option>
<option value="Hesaraghatta">Hesaraghatta</option>
<option value="Highgrounds">Highgrounds</option>
<option value="HMT Layout">HMT Layout</option>
<option value="Hootagalli">Hootagalli</option>
<option value="Hope Form">Hope Form</option>
<option value="Horamavu">Horamavu</option>
<option value="Hosakerehalli">Hosakerehalli</option>
<option value="Hoskote">Hoskote</option>
<option value="Hospet">Hospet</option>
<option value="Hosur Road">Hosur Road</option>
<option value="Hoysala Nagar">Hoysala Nagar</option>
<option value="HRBR Layout">HRBR Layout</option>
<option value="HSR Layout">HSR Layout</option>
<option value="Hunsur Road">Hunsur Road</option>
<option value="Indiranagar">Indiranagar</option>
<option value="Indiranagar, Mysore">Indiranagar, Mysore</option>
<option value="Industrial state">Industrial state</option>
<option value="Infantry Road">Infantry Road</option>
<option value="Infantry Road">Infantry Road</option>
<option value="Irwin Road">Irwin Road</option>
<option value="ISRO Layout">ISRO Layout</option>
<option value="ITI Colony">ITI Colony</option>
<option value="ITPL">ITPL</option>
<option value="Ittige Gudu">Ittige Gudu</option>
<option value="Jail Road">Jail Road</option>
<option value="Jakkur">Jakkur</option>
<option value="Jalahalli">Jalahalli</option>
<option value="Jambunath Road">Jambunath Road</option>
<option value="Jayalakshmipuram">Jayalakshmipuram</option>
<option value="Jayamahal Road">Jayamahal Road</option>
<option value="Jayanagar">Jayanagar</option>
<option value="Jayanagar ">Jayanagar </option>
<option value="Jayapura Hobli">Jayapura Hobli</option>
<option value="JC Nagar">JC Nagar</option>
<option value="JC Road">JC Road</option>
<option value="Jeevanbheema Nagar">Jeevanbheema Nagar</option>
<option value="JLB Road">JLB Road</option>
<option value="Jnana Bharathi">Jnana Bharathi</option>
<option value="Jogupalya">Jogupalya</option>
<option value="JP Nagar">JP Nagar</option>
<option value="Judicial Layout">Judicial Layout</option>
<option value="K R Mohalla">K R Mohalla</option>
<option value="Kachalakki Keri">Kachalakki Keri</option>
<option value="Kacharakana Halli">Kacharakana Halli</option>
<option value="Kadirenahalli">Kadirenahalli</option>
<option value="Kadubeesanahalli">Kadubeesanahalli</option>
<option value="Kadugodi">Kadugodi</option>
<option value="Kaggadasapura">Kaggadasapura</option>
<option value="Kaikondrahalli">Kaikondrahalli</option>
<option value="Kalamma Street">Kalamma Street</option>
<option value="Kalasipalayam">Kalasipalayam</option>
<option value="Kali Temple Road">Kali Temple Road</option>
<option value="Kalkere">Kalkere</option>
<option value="Kalyan Nagar">Kalyan Nagar</option>
<option value="Kamakshi Palya">Kamakshi Palya</option>
<option value="Kamala Nagar">Kamala Nagar</option>
<option value="Kamalapur Post">Kamalapur Post</option>
<option value="Kammanahalli Main Road">Kammanahalli Main Road</option>
<option value="Kamraj Road">Kamraj Road</option>
<option value="Kanakapura Road">Kanakapura Road</option>
<option value="Kasturba Road">Kasturba Road</option>
<option value="Kasturi Nagar">Kasturi Nagar</option>
<option value="Kathriguppe Main Road">Kathriguppe Main Road</option>
<option value="Kavalbyrasandra">Kavalbyrasandra</option>
<option value="KEB Layout">KEB Layout</option>
<option value="Kempaura">Kempaura</option>
<option value="Kempe Gowda Road">Kempe Gowda Road</option>
<option value="Kengeri">Kengeri</option>
<option value="Kengeri Satellite Town">Kengeri Satellite Town</option>
<option value="KH Road">KH Road</option>
<option value="KHB Road">KHB Road</option>
<option value="Kodihalli">Kodihalli</option>
<option value="Konankunte">Konankunte</option>
<option value="Koorgalli">Koorgalli</option>
<option value="Koramangala">Koramangala</option>
<option value="Kote Road">Kote Road</option>
<option value="Kothanur">Kothanur</option>
<option value="Kotnur Dinne">Kotnur Dinne</option>
<option value="KR Puram">KR Puram</option>
<option value="Krishnarajapuram">Krishnarajapuram</option>
<option value="KRS Road">KRS Road</option>
<option value="Kudligi Road">Kudligi Road</option>
<option value="Kudlu">Kudlu</option>
<option value="Kumara Park">Kumara Park</option>
<option value="Kumaraswamy Layout">Kumaraswamy Layout</option>
<option value="Kumbalgodu">Kumbalgodu</option>
<option value="Kundalahalli">Kundalahalli</option>
<option value="Kurubarahalli">Kurubarahalli</option>
<option value="Kuvempu Nagar">Kuvempu Nagar</option>
<option value="Kuvempu Road">Kuvempu Road</option>
<option value="Laggere">Laggere</option>
<option value="Lakkasandra">Lakkasandra</option>
<option value="Lakshminarayanapuram">Lakshminarayanapuram</option>
<option value="Lakshmipuram">Lakshmipuram</option>
<option value="Lalbagh Road">Lalbagh Road</option>
<option value="Lalithadripura">Lalithadripura</option>
<option value="Langford Road">Langford Road</option>
<option value="Lashkar Mohalla">Lashkar Mohalla</option>
<option value="Lavelle Road">Lavelle Road</option>
<option value="Lingarajapuram">Lingarajapuram</option>
<option value="Lottegollahalli">Lottegollahalli</option>
<option value="M G Road (Mysore)">M G Road (Mysore)</option>
<option value="M S Ramaiah Nagar">M S Ramaiah Nagar</option>
<option value="Madanayakahalli">Madanayakahalli</option>
<option value="Madikere">Madikere</option>
<option value="Madiwala">Madiwala</option>
<option value="Madras Bank Road">Madras Bank Road</option>
<option value="Magadi Road">Magadi Road</option>
<option value="Magrath Road">Magrath Road</option>
<option value="Mahadevapura">Mahadevapura</option>
<option value="Mahalakshmi Layout">Mahalakshmi Layout</option>
<option value="Majestic Area">Majestic Area</option>
<option value="Malleshpalya">Malleshpalya</option>
<option value="Malleshwaram">Malleshwaram</option>
<option value="Manandavadi Road">Manandavadi Road</option>
<option value="Manasagangotri">Manasagangotri</option>
<option value="Mandi Mohalla">Mandi Mohalla</option>
<option value="Manjunatha Nagar">Manjunatha Nagar</option>
<option value="Marathahalli">Marathahalli</option>
<option value="Maruthi Extn">Maruthi Extn</option>
<option value="Maruthi Nagar">Maruthi Nagar</option>
<option value="Maruthiseva Nagar">Maruthiseva Nagar</option>
<option value="Mathikere">Mathikere</option>
<option value="Mavalli">Mavalli</option>
<option value="Mayo Hall">Mayo Hall</option>
<option value="Metagalli">Metagalli</option>
<option value="MG Road">MG Road</option>
<option value="MICO Layout">MICO Layout</option>
<option value="Millagatta">Millagatta</option>
<option value="Millers Road">Millers Road</option>
<option value="Minirabad Road">Minirabad Road</option>
<option value="Mission Road">Mission Road</option>
<option value="MM Road">MM Road</option>
<option value="Mothi Circle">Mothi Circle</option>
<option value="Munireddy Palya">Munireddy Palya</option>
<option value="Murgesh Palya">Murgesh Palya</option>
<option value="Museum Road">Museum Road</option>
<option value="Mysore Road">Mysore Road</option>
<option value="N S Road">N S Road</option>
<option value="N T Road">N T Road</option>
<option value="Nagarabhavi">Nagarabhavi</option>
<option value="Nagarathpet">Nagarathpet</option>
<option value="Nagarvar Kari">Nagarvar Kari</option>
<option value="Nagasandra">Nagasandra</option>
<option value="Nagashettyhalli">Nagashettyhalli</option>
<option value="Nagavara">Nagavara</option>
<option value="Naguvanahalli">Naguvanahalli</option>
<option value="Nandidurg Road">Nandidurg Road</option>
<option value="Nandini Layout">Nandini Layout</option>
<option value="Navule">Navule</option>
<option value="Nayandahalli">Nayandahalli</option>
<option value="Nazarbad">Nazarbad</option>
<option value="Nehru Road">Nehru Road</option>
<option value="Nelamangala">Nelamangala</option>
<option value="New BEL Road">New BEL Road</option>
<option value="New Thippasandra">New Thippasandra</option>
<option value="New Trunk Road">New Trunk Road</option>
<option value="Nilasandra">Nilasandra</option>
<option value="NR Colony">NR Colony</option>
<option value="O T Road">O T Road</option>
<option value="Okalipuram">Okalipuram</option>
<option value="Old Bank Road">Old Bank Road</option>
<option value="Old Madras Road">Old Madras Road</option>
<option value="OTC Road">OTC Road</option>
<option value="Outer Ring Road">Outer Ring Road</option>
<option value="Padmanabhanagar">Padmanabhanagar</option>
<option value="Pai Layout">Pai Layout</option>
<option value="Palace Orchards">Palace Orchards</option>
<option value="Palace Road">Palace Road</option>
<option value="Parvathi Nagar">Parvathi Nagar</option>
<option value="Peenya Industrial Area">Peenya Industrial Area</option>
<option value="Pillangere">Pillangere</option>
<option value="Primrose Road">Primrose Road</option>
<option value="Pulikeshinagar">Pulikeshinagar</option>
<option value="Queens Road">Queens Road</option>
<option value="R T Nagar, Mysore">R T Nagar, Mysore</option>
<option value="R V Niketan">R V Niketan</option>
<option value="Race Course Road">Race Course Road</option>
<option value="Rahmat Nagar">Rahmat Nagar</option>
<option value="Raj Bhavan Road">Raj Bhavan Road</option>
<option value="Raj Mahal Vilas Extension">Raj Mahal Vilas Extension</option>
<option value="Raja Ram Mohan Roy Road">Raja Ram Mohan Roy Road</option>
<option value="Rajajinagar">Rajajinagar</option>
<option value="Rajarajeshwari Nagar">Rajarajeshwari Nagar</option>
<option value="Rajendra Nagar">Rajendra Nagar</option>
<option value="Ramamurthy Nagar">Ramamurthy Nagar</option>
<option value="Ramanuja Road">Ramanuja Road</option>
<option value="Ramvilas Road">Ramvilas Road</option>
<option value="Ravindra Nagar">Ravindra Nagar</option>
<option value="Residency Road">Residency Road</option>
<option value="Rest House Road">Rest House Road</option>
<option value="Richards Town">Richards Town</option>
<option value="Richmond Road">Richmond Road</option>
<option value="Richmond Town">Richmond Town</option>
<option value="Ring Road">Ring Road</option>
<option value="RMV Extension">RMV Extension</option>
<option value="RPC Layout">RPC Layout</option>
<option value="RT Nagar">RT Nagar</option>
<option value="RV Road">RV Road</option>
<option value="S Iyer Road">S Iyer Road</option>
<option value="S. R. Nagar">S. R. Nagar</option>
<option value="Sadahalli">Sadahalli</option>
<option value="Sadashivnagar">Sadashivnagar</option>
<option value="Sagar Taluk">Sagar Taluk</option>
<option value="Sagayapura">Sagayapura</option>
<option value="Sahakara Nagar">Sahakara Nagar</option>
<option value="Sajjan Rao Circle">Sajjan Rao Circle</option>
<option value="Sampangiram Nagar">Sampangiram Nagar</option>
<option value="Sandur">Sandur</option>
<option value="Sanjay Nagar">Sanjay Nagar</option>
<option value="Sankarapuram">Sankarapuram</option>
<option value="Sankey Road Cross">Sankey Road Cross</option>
<option value="Sarakki">Sarakki</option>
<option value="Saraswathipuram">Saraswathipuram</option>
<option value="Sarjapur Road">Sarjapur Road</option>
<option value="Sarvagna Nagar">Sarvagna Nagar</option>
<option value="Savarline Road">Savarline Road</option>
<option value="Savlanga Road">Savlanga Road</option>
<option value="Sayyaji Rao Road">Sayyaji Rao Road</option>
<option value="Seshadripuram">Seshadripuram</option>
<option value="Sevashrama">Sevashrama</option>
<option value="Shakthi Nagar">Shakthi Nagar</option>
<option value="Shankaraghatta">Shankaraghatta</option>
<option value="Shanthala Nagar">Shanthala Nagar</option>
<option value="Shanthiniketan Layout">Shanthiniketan Layout</option>
<option value="Shantinagar">Shantinagar</option>
<option value="Sharavathi Nagar">Sharavathi Nagar</option>
<option value="Shastri Nagar">Shastri Nagar</option>
<option value="Sheshadri Puram">Sheshadri Puram</option>
<option value="Shivajinagar">Shivajinagar</option>
<option value="Shivamurthi Circle">Shivamurthi Circle</option>
<option value="Shivarampet">Shivarampet</option>
<option value="Shri Harsha Road">Shri Harsha Road</option>
<option value="Siddartha Nagar">Siddartha Nagar</option>
<option value="Sindhi Colony">Sindhi Colony</option>
<option value="Singha Sandra">Singha Sandra</option>
<option value="Sivanchetty Garden">Sivanchetty Garden</option>
<option value="Somnathpura">Somnathpura</option>
<option value="Soraba Taluk">Soraba Taluk</option>
<option value="Srinagar">Srinagar</option>
<option value="Srinivasa Nagar">Srinivasa Nagar</option>
<option value="Srirampura ">Srirampura </option>
<option value="Srirampuram">Srirampuram</option>
<option value="SS Nagar">SS Nagar</option>
<option value="St. Johns Church Road">St. Johns Church Road</option>
<option value="St. Marks Road">St. Marks Road</option>
<option value="St. Thomas Town">St. Thomas Town</option>
<option value="Station Road">Station Road</option>
<option value="Subanna Palya">Subanna Palya</option>
<option value="Subramanyapura">Subramanyapura</option>
<option value="Sudhama Nagar">Sudhama Nagar</option>
<option value="Sultanpet">Sultanpet</option>
<option value="Sunkadakatte">Sunkadakatte</option>
<option value="Sunkenahalli">Sunkenahalli</option>
<option value="T Narasipura Road">T Narasipura Road</option>
<option value="T.Dasarahalli">T.Dasarahalli</option>
<option value="Talguppa">Talguppa</option>
<option value="Tarabanahalli">Tarabanahalli</option>
<option value="Telecom Layout">Telecom Layout</option>
<option value="Temple Road">Temple Road</option>
<option value="Thanisandra Main Road">Thanisandra Main Road</option>
<option value="Thubarahalli">Thubarahalli</option>
<option value="Thyagaraja Road">Thyagaraja Road</option>
<option value="Thyagarajanagar">Thyagarajanagar</option>
<option value="Tilak Nagar">Tilak Nagar</option>
<option value="Tilak Nagar">Tilak Nagar</option>
<option value="Timber Yard">Timber Yard</option>
<option value="Tirthahalli">Tirthahalli</option>
<option value="TK Layout">TK Layout</option>
<option value="Tumkur Road">Tumkur Road</option>
<option value="Tunga">Tunga</option>
<option value="Udayagiri">Udayagiri</option>
<option value="Ulsoor">Ulsoor</option>
<option value="Umar Khayam Road">Umar Khayam Road</option>
<option value="Uttarahalli Main Road">Uttarahalli Main Road</option>
<option value="V.V.Mohalla">V.V.Mohalla</option>
<option value="Varthur">Varthur</option>
<option value="Vasanthapura">Vasanthapura</option>
<option value="Vasanthnagar">Vasanthnagar</option>
<option value="Venkatapura">Venkatapura</option>
<option value="Victoria Road">Victoria Road</option>
<option value="Vidhyaranya Road">Vidhyaranya Road</option>
<option value="Vidya Peetha">Vidya Peetha</option>
<option value="Vidyaranyapura">Vidyaranyapura</option>
<option value="Vidyaranyapuram">Vidyaranyapuram</option>
<option value="Vignan Nagar">Vignan Nagar</option>
<option value="Vijayanagar">Vijayanagar</option>
<option value="Vijaynagar">Vijaynagar</option>
<option value="Vimanapura">Vimanapura</option>
<option value="Vinayaka Layout">Vinayaka Layout</option>
<option value="Vinayaka Nagar">Vinayaka Nagar</option>
<option value="Vinayakanagara">Vinayakanagara</option>
<option value="Vinobha Nagara">Vinobha Nagara</option>
<option value="Vishveshwara Circle">Vishveshwara Circle</option>
<option value="Vishweshwara Nagar">Vishweshwara Nagar</option>
<option value="Visveshwarapuram">Visveshwarapuram</option>
<option value="Vittal Mallya Road">Vittal Mallya Road</option>
<option value="Viveknagar">Viveknagar</option>
<option value="VV Puram">VV Puram</option>
<option value="Vyalikaval">Vyalikaval</option>
<option value="West of Chord Road">West of Chord Road</option>
<option value="Wheeler Road">Wheeler Road</option>
<option value="Whitefield">Whitefield</option>
<option value="Wilson Garden">Wilson Garden</option>
<option value="Yadavagiri">Yadavagiri</option>
<option value="Yediyur">Yediyur</option>
<option value="Yelahanka">Yelahanka</option>
<option value="Yelahanka New Town">Yelahanka New Town</option>
<option value="Yeshwanthpur">Yeshwanthpur</option>
